# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import libros_pb2 as libros__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in libros_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LibroServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearLibro = channel.unary_unary(
                '/libros.LibroService/CrearLibro',
                request_serializer=libros__pb2.Libro.SerializeToString,
                response_deserializer=libros__pb2.Respuesta.FromString,
                _registered_method=True)
        self.ObtenerLibro = channel.unary_unary(
                '/libros.LibroService/ObtenerLibro',
                request_serializer=libros__pb2.LibroId.SerializeToString,
                response_deserializer=libros__pb2.Libro.FromString,
                _registered_method=True)
        self.ActualizarLibro = channel.unary_unary(
                '/libros.LibroService/ActualizarLibro',
                request_serializer=libros__pb2.Libro.SerializeToString,
                response_deserializer=libros__pb2.Respuesta.FromString,
                _registered_method=True)
        self.EliminarLibro = channel.unary_unary(
                '/libros.LibroService/EliminarLibro',
                request_serializer=libros__pb2.LibroId.SerializeToString,
                response_deserializer=libros__pb2.Respuesta.FromString,
                _registered_method=True)
        self.ListarLibros = channel.unary_unary(
                '/libros.LibroService/ListarLibros',
                request_serializer=libros__pb2.Vacio.SerializeToString,
                response_deserializer=libros__pb2.ListaLibros.FromString,
                _registered_method=True)


class LibroServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CrearLibro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerLibro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarLibro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarLibro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarLibros(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibroServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearLibro': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearLibro,
                    request_deserializer=libros__pb2.Libro.FromString,
                    response_serializer=libros__pb2.Respuesta.SerializeToString,
            ),
            'ObtenerLibro': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerLibro,
                    request_deserializer=libros__pb2.LibroId.FromString,
                    response_serializer=libros__pb2.Libro.SerializeToString,
            ),
            'ActualizarLibro': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarLibro,
                    request_deserializer=libros__pb2.Libro.FromString,
                    response_serializer=libros__pb2.Respuesta.SerializeToString,
            ),
            'EliminarLibro': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarLibro,
                    request_deserializer=libros__pb2.LibroId.FromString,
                    response_serializer=libros__pb2.Respuesta.SerializeToString,
            ),
            'ListarLibros': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarLibros,
                    request_deserializer=libros__pb2.Vacio.FromString,
                    response_serializer=libros__pb2.ListaLibros.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'libros.LibroService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('libros.LibroService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LibroService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CrearLibro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/libros.LibroService/CrearLibro',
            libros__pb2.Libro.SerializeToString,
            libros__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerLibro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/libros.LibroService/ObtenerLibro',
            libros__pb2.LibroId.SerializeToString,
            libros__pb2.Libro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarLibro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/libros.LibroService/ActualizarLibro',
            libros__pb2.Libro.SerializeToString,
            libros__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarLibro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/libros.LibroService/EliminarLibro',
            libros__pb2.LibroId.SerializeToString,
            libros__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarLibros(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/libros.LibroService/ListarLibros',
            libros__pb2.Vacio.SerializeToString,
            libros__pb2.ListaLibros.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
