# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: libros.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'libros.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clibros.proto\x12\x06libros\"L\n\x05Libro\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\r\n\x05\x61utor\x18\x03 \x01(\t\x12\x18\n\x10\x61nio_publicacion\x18\x04 \x01(\x05\"\x15\n\x07LibroId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1c\n\tRespuesta\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\"\x07\n\x05Vacio\",\n\x0bListaLibros\x12\x1d\n\x06libros\x18\x01 \x03(\x0b\x32\r.libros.Libro2\x8c\x02\n\x0cLibroService\x12.\n\nCrearLibro\x12\r.libros.Libro\x1a\x11.libros.Respuesta\x12.\n\x0cObtenerLibro\x12\x0f.libros.LibroId\x1a\r.libros.Libro\x12\x33\n\x0f\x41\x63tualizarLibro\x12\r.libros.Libro\x1a\x11.libros.Respuesta\x12\x33\n\rEliminarLibro\x12\x0f.libros.LibroId\x1a\x11.libros.Respuesta\x12\x32\n\x0cListarLibros\x12\r.libros.Vacio\x1a\x13.libros.ListaLibrosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'libros_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIBRO']._serialized_start=24
  _globals['_LIBRO']._serialized_end=100
  _globals['_LIBROID']._serialized_start=102
  _globals['_LIBROID']._serialized_end=123
  _globals['_RESPUESTA']._serialized_start=125
  _globals['_RESPUESTA']._serialized_end=153
  _globals['_VACIO']._serialized_start=155
  _globals['_VACIO']._serialized_end=162
  _globals['_LISTALIBROS']._serialized_start=164
  _globals['_LISTALIBROS']._serialized_end=208
  _globals['_LIBROSERVICE']._serialized_start=211
  _globals['_LIBROSERVICE']._serialized_end=479
# @@protoc_insertion_point(module_scope)
